---
- hosts: test-server3
  become: true
  tasks:
  - name: update apt
    command: apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: deploy healthcare application
    command: sudo docker run -itd -p 8083:8083 --name healthcare prasad996600/healthcare:1.0
